# Generated by Django 4.0.1 on 2022-01-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, null=True, to='core.Acessorio'),
        ),
    ]
